// MOVIE TYPES
export const FETCH_MOVIE_REQUEST = "FETCH_MOVIE_REQUEST";
export const FETCH_MOVIE_SUCCEEDED = "FETCH_MOVIE_SUCCEEDED";

export const FETCH_MOVIE_DETAIL_REQUEST = "FETCH_MOVIE_DETAIL_REQUEST";
export const FETCH_MOVIE_DETAIL_SUCCEEDED = "FETCH_MOVIE_DETAIL_SUCCEEDED";

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCEEDED = "DELETE_MOVIE_SUCCEEDED";

export const LIKE_UNLIKE_MOVIE_REQUEST = "LIKE_UNLIKE_MOVIE_REQUEST";
export const LIKE_UNLIKE_MOVIE_SUCCEEDED = "LIKE_UNLIKE_MOVIE_SUCCEEDED";

export const PAGINATION_MOVIE_REQUEST = "PAGINATION_MOVIE_REQUEST";
export const PAGINATION_MOVIE_SUCCEEDED = "PAGINATION_MOVIE_SUCCEEDED";

export const CHANGE_PAGINATION_MOVIE = "CHANGE_PAGINATION_MOVIE";

export const FILTER_BY_GENRE_REQUEST = "FILTER_BY_GENRE_REQUEST";
export const FILTER_BY_GENRE_SUCCEEDED = "FILTER_BY_GENRE_SUCCEEDED";

export const SORT_MOVIE_REQUEST = "SORT_MOVIE_REQUEST";
export const SORT_MOVIE_SUCCEEDED = "SORT_MOVIE_SUCCEEDED";

export const SAVE_MOVIE_REQUEST = "SAVE_MOVIE_REQUEST";
export const SAVE_MOVIE_SUCCEEDED = "SAVE_MOVIE_SUCCEEDED";

export const CREATE_MOVIE_REQUEST = "CREATE_MOVIE_REQUEST";
export const CREATE_MOVIE_SUCCEEDED = "CREATE_MOVIE_SUCCEEDED";

export const SERACH_MOVIE_REQUEST = "SERACH_MOVIE_REQUEST";
export const SERACH_MOVIE_SUCCEEDED = "SERACH_MOVIE_SUCCEEDED";

// AUTH TYPES
export const REGISTER_USER = "REGISTER_USER";

export const LOGIN_USER = "LOGIN_USER";

export const LOGOUT_USER = "LOGOUT_USER";

export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCEEDED = "AUTHENTICATION_SUCCEEDED";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";

export const GET_USER = "GET_USER";

// UTIL TYPES
export const LOADING_DATA = "LOADING_DATA";
export const LOADED_DATA = "LOADED_DATA";

export const GET_TYPE_NAME_TOAST = "GET_TYPE_NAME_TOAST";

export const SHOW_TOAST_SUCCEEDED = "SHOW_TOAST_SUCCEEDED";
export const SHOW_TOAST_ERROR = "SHOW_TOAST_ERROR";

//ERROR TYPES
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
